/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatImportForm {
    #[serde(rename = "chat")]
    pub chat: serde_json::Value,
    #[serde(
        rename = "meta",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub meta: Option<Option<serde_json::Value>>,
    #[serde(
        rename = "pinned",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub pinned: Option<Option<bool>>,
    #[serde(
        rename = "folder_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub folder_id: Option<Option<String>>,
}

impl ChatImportForm {
    pub fn new(chat: serde_json::Value) -> ChatImportForm {
        ChatImportForm {
            chat,
            meta: None,
            pinned: None,
            folder_id: None,
        }
    }
}
