/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatIdTagModel {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "tag_name")]
    pub tag_name: String,
    #[serde(rename = "chat_id")]
    pub chat_id: String,
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(rename = "timestamp")]
    pub timestamp: i32,
}

impl ChatIdTagModel {
    pub fn new(
        id: String,
        tag_name: String,
        chat_id: String,
        user_id: String,
        timestamp: i32,
    ) -> ChatIdTagModel {
        ChatIdTagModel {
            id,
            tag_name,
            chat_id,
            user_id,
            timestamp,
        }
    }
}
