/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileModel {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(
        rename = "hash",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub hash: Option<Option<String>>,
    #[serde(rename = "filename")]
    pub filename: String,
    #[serde(
        rename = "data",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub data: Option<Option<serde_json::Value>>,
    #[serde(rename = "meta")]
    pub meta: serde_json::Value,
    #[serde(rename = "created_at")]
    pub created_at: i32,
    #[serde(rename = "updated_at")]
    pub updated_at: i32,
}

impl FileModel {
    pub fn new(
        id: String,
        user_id: String,
        filename: String,
        meta: serde_json::Value,
        created_at: i32,
        updated_at: i32,
    ) -> FileModel {
        FileModel {
            id,
            user_id,
            hash: None,
            filename,
            data: None,
            meta,
            created_at,
            updated_at,
        }
    }
}
