/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "meta")]
    pub meta: models::ModelMeta,
    #[serde(rename = "updated_at")]
    pub updated_at: i32,
    #[serde(rename = "created_at")]
    pub created_at: i32,
}

impl ModelResponse {
    pub fn new(
        id: String,
        name: String,
        meta: models::ModelMeta,
        updated_at: i32,
        created_at: i32,
    ) -> ModelResponse {
        ModelResponse {
            id,
            name,
            meta,
            updated_at,
            created_at,
        }
    }
}
