/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelForm {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(
        rename = "base_model_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub base_model_id: Option<Option<String>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "meta")]
    pub meta: models::ModelMeta,
    #[serde(rename = "params")]
    pub params: std::collections::HashMap<String, serde_json::Value>,
}

impl ModelForm {
    pub fn new(
        id: String,
        name: String,
        meta: models::ModelMeta,
        params: std::collections::HashMap<String, serde_json::Value>,
    ) -> ModelForm {
        ModelForm {
            id,
            base_model_id: None,
            name,
            meta,
            params,
        }
    }
}
