/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpenWebuiAppsWebuiRoutersUsersUserResponse {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "profile_image_url")]
    pub profile_image_url: String,
}

impl OpenWebuiAppsWebuiRoutersUsersUserResponse {
    pub fn new(
        name: String,
        profile_image_url: String,
    ) -> OpenWebuiAppsWebuiRoutersUsersUserResponse {
        OpenWebuiAppsWebuiRoutersUsersUserResponse {
            name,
            profile_image_url,
        }
    }
}
