/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpenWebuiAppsWebuiRoutersUtilsChatForm {
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "messages")]
    pub messages: Vec<serde_json::Value>,
}

impl OpenWebuiAppsWebuiRoutersUtilsChatForm {
    pub fn new(
        title: String,
        messages: Vec<serde_json::Value>,
    ) -> OpenWebuiAppsWebuiRoutersUtilsChatForm {
        OpenWebuiAppsWebuiRoutersUtilsChatForm { title, messages }
    }
}
