/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PromptModel {
    #[serde(rename = "command")]
    pub command: String,
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "timestamp")]
    pub timestamp: i32,
}

impl PromptModel {
    pub fn new(
        command: String,
        user_id: String,
        title: String,
        content: String,
        timestamp: i32,
    ) -> PromptModel {
        PromptModel {
            command,
            user_id,
            title,
            content,
            timestamp,
        }
    }
}
