/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryMemoryForm {
    #[serde(rename = "content")]
    pub content: String,
    #[serde(
        rename = "k",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub k: Option<Option<i32>>,
}

impl QueryMemoryForm {
    pub fn new(content: String) -> QueryMemoryForm {
        QueryMemoryForm { content, k: None }
    }
}
