/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetDefaultModelsForm {
    #[serde(rename = "models")]
    pub models: String,
}

impl SetDefaultModelsForm {
    pub fn new(models: String) -> SetDefaultModelsForm {
        SetDefaultModelsForm { models }
    }
}
