/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ToolModel {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "specs")]
    pub specs: Vec<serde_json::Value>,
    #[serde(rename = "meta")]
    pub meta: Box<models::ToolMeta>,
    #[serde(rename = "updated_at")]
    pub updated_at: i32,
    #[serde(rename = "created_at")]
    pub created_at: i32,
}

impl ToolModel {
    pub fn new(
        id: String,
        user_id: String,
        name: String,
        content: String,
        specs: Vec<serde_json::Value>,
        meta: models::ToolMeta,
        updated_at: i32,
        created_at: i32,
    ) -> ToolModel {
        ToolModel {
            id,
            user_id,
            name,
            content,
            specs,
            meta: Box::new(meta),
            updated_at,
            created_at,
        }
    }
}
