/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ToolResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "meta")]
    pub meta: Box<models::ToolMeta>,
    #[serde(rename = "updated_at")]
    pub updated_at: i32,
    #[serde(rename = "created_at")]
    pub created_at: i32,
}

impl ToolResponse {
    pub fn new(
        id: String,
        user_id: String,
        name: String,
        meta: models::ToolMeta,
        updated_at: i32,
        created_at: i32,
    ) -> ToolResponse {
        ToolResponse {
            id,
            user_id,
            name,
            meta: Box::new(meta),
            updated_at,
            created_at,
        }
    }
}
