/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ToolForm {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "meta")]
    pub meta: Box<models::ToolMeta>,
}

impl ToolForm {
    pub fn new(id: String, name: String, content: String, meta: models::ToolMeta) -> ToolForm {
        ToolForm {
            id,
            name,
            content,
            meta: Box::new(meta),
        }
    }
}
