/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateConfigForm {
    #[serde(
        rename = "ENABLE_EVALUATION_ARENA_MODELS",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub enable_evaluation_arena_models: Option<Option<bool>>,
    #[serde(
        rename = "EVALUATION_ARENA_MODELS",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub evaluation_arena_models: Option<Option<Vec<serde_json::Value>>>,
}

impl UpdateConfigForm {
    pub fn new() -> UpdateConfigForm {
        UpdateConfigForm {
            enable_evaluation_arena_models: None,
            evaluation_arena_models: None,
        }
    }
}
