/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateProfileForm {
    #[serde(rename = "profile_image_url")]
    pub profile_image_url: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl UpdateProfileForm {
    pub fn new(profile_image_url: String, name: String) -> UpdateProfileForm {
        UpdateProfileForm {
            profile_image_url,
            name,
        }
    }
}
