/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserSettings {
    #[serde(rename = "ui", skip_serializing_if = "Option::is_none")]
    pub ui: Option<Box<models::Ui>>,
}

impl UserSettings {
    pub fn new() -> UserSettings {
        UserSettings { ui: None }
    }
}
