/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserRoleUpdateForm {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "role")]
    pub role: String,
}

impl UserRoleUpdateForm {
    pub fn new(id: String, role: String) -> UserRoleUpdateForm {
        UserRoleUpdateForm { id, role }
    }
}
