/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserModel {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    #[serde(rename = "profile_image_url")]
    pub profile_image_url: String,
    #[serde(rename = "last_active_at")]
    pub last_active_at: i32,
    #[serde(rename = "updated_at")]
    pub updated_at: i32,
    #[serde(rename = "created_at")]
    pub created_at: i32,
    #[serde(
        rename = "api_key",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub api_key: Option<Option<String>>,
    #[serde(
        rename = "settings",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub settings: Option<Option<models::UserSettings>>,
    #[serde(
        rename = "info",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub info: Option<Option<serde_json::Value>>,
    #[serde(
        rename = "oauth_sub",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub oauth_sub: Option<Option<String>>,
}

impl UserModel {
    pub fn new(
        id: String,
        name: String,
        email: String,
        profile_image_url: String,
        last_active_at: i32,
        updated_at: i32,
        created_at: i32,
    ) -> UserModel {
        UserModel {
            id,
            name,
            email,
            role: None,
            profile_image_url,
            last_active_at,
            updated_at,
            created_at,
            api_key: None,
            settings: None,
            info: None,
            oauth_sub: None,
        }
    }
}
