/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileConfig {
    #[serde(rename = "max_size", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_size: Option<Option<i32>>,
    #[serde(rename = "max_count", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_count: Option<Option<i32>>,
}

impl FileConfig {
    pub fn new() -> FileConfig {
        FileConfig {
            max_size: None,
            max_count: None,
        }
    }
}

