/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpenAiConfigForm {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "key")]
    pub key: String,
}

impl OpenAiConfigForm {
    pub fn new(url: String, key: String) -> OpenAiConfigForm {
        OpenAiConfigForm { url, key }
    }
}
