/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProcessFileForm {
    #[serde(rename = "file_id")]
    pub file_id: String,
    #[serde(
        rename = "content",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub content: Option<Option<String>>,
    #[serde(
        rename = "collection_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub collection_name: Option<Option<String>>,
}

impl ProcessFileForm {
    pub fn new(file_id: String) -> ProcessFileForm {
        ProcessFileForm {
            file_id,
            content: None,
            collection_name: None,
        }
    }
}
