[package]
name = "owui-ollama"
version.workspace = true
edition.workspace = true
publish = false

# dependencies moved to my-common
[dependencies]
my-common = { path = "../my-common" }
my-workspace-hack = { version = "0.1", path = "../my-workspace-hack" }
