/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaskConfigForm {
    #[serde(rename = "TASK_MODEL", deserialize_with = "Option::deserialize")]
    pub task_model: Option<String>,
    #[serde(
        rename = "TASK_MODEL_EXTERNAL",
        deserialize_with = "Option::deserialize"
    )]
    pub task_model_external: Option<String>,
    #[serde(rename = "TITLE_GENERATION_PROMPT_TEMPLATE")]
    pub title_generation_prompt_template: String,
    #[serde(rename = "TAGS_GENERATION_PROMPT_TEMPLATE")]
    pub tags_generation_prompt_template: String,
    #[serde(rename = "SEARCH_QUERY_GENERATION_PROMPT_TEMPLATE")]
    pub search_query_generation_prompt_template: String,
    #[serde(rename = "ENABLE_SEARCH_QUERY")]
    pub enable_search_query: bool,
    #[serde(rename = "TOOLS_FUNCTION_CALLING_PROMPT_TEMPLATE")]
    pub tools_function_calling_prompt_template: String,
}

impl TaskConfigForm {
    pub fn new(
        task_model: Option<String>,
        task_model_external: Option<String>,
        title_generation_prompt_template: String,
        tags_generation_prompt_template: String,
        search_query_generation_prompt_template: String,
        enable_search_query: bool,
        tools_function_calling_prompt_template: String,
    ) -> TaskConfigForm {
        TaskConfigForm {
            task_model,
            task_model_external,
            title_generation_prompt_template,
            tags_generation_prompt_template,
            search_query_generation_prompt_template,
            enable_search_query,
            tools_function_calling_prompt_template,
        }
    }
}
