/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigUpdateForm {
    #[serde(rename = "pdf_extract_images", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pdf_extract_images: Option<Option<bool>>,
    #[serde(rename = "file", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub file: Option<Option<Box<models::FileConfig>>>,
    #[serde(rename = "content_extraction", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub content_extraction: Option<Option<Box<models::ContentExtractionConfig>>>,
    #[serde(rename = "chunk", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub chunk: Option<Option<Box<models::ChunkParamUpdateForm>>>,
    #[serde(rename = "youtube", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub youtube: Option<Option<Box<models::YoutubeLoaderConfig>>>,
    #[serde(rename = "web", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub web: Option<Option<Box<models::WebConfig>>>,
}

impl ConfigUpdateForm {
    pub fn new() -> ConfigUpdateForm {
        ConfigUpdateForm {
            pdf_extract_images: None,
            file: None,
            content_extraction: None,
            chunk: None,
            youtube: None,
            web: None,
        }
    }
}

