/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmbeddingModelUpdateForm {
    #[serde(rename = "openai_config", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub openai_config: Option<Option<Box<models::OpenAiConfigForm>>>,
    #[serde(rename = "embedding_engine")]
    pub embedding_engine: String,
    #[serde(rename = "embedding_model")]
    pub embedding_model: String,
}

impl EmbeddingModelUpdateForm {
    pub fn new(embedding_engine: String, embedding_model: String) -> EmbeddingModelUpdateForm {
        EmbeddingModelUpdateForm {
            openai_config: None,
            embedding_engine,
            embedding_model,
        }
    }
}

