/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PushModelForm {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(
        rename = "insecure",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub insecure: Option<Option<bool>>,
    #[serde(
        rename = "stream",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub stream: Option<Option<bool>>,
}

impl PushModelForm {
    pub fn new(name: String) -> PushModelForm {
        PushModelForm {
            name,
            insecure: None,
            stream: None,
        }
    }
}
